version: '3.7'
services: 
  ngnix:
    image: ngnix:stable-alpie
    container_name: ngnix
    restart: always 
    ports:
      - 8888:80

    volumes: 
      - ./src:/var/ww/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php
      - mysql
    
    networks:
      - laravel


  mysql: 
    image: mysql:5.7
    container_name: mysql
    restart: always 
    environment: 
      MYSQL_DATABASE: poli
      MYSQL_USER: poli
      MYSQL_PASSEORD: secret
      MYSQL_ROOT_PASSWORD: admin.root
    ports:
      - 33069:3306
      
    volumes:
      - ./mysql:/var/lib/mysql
    
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes: 
      - ./src:/var/html
    ports: 
      - 9000:80
    networks:
      - laravel
  
networks:
  laravel:
